name: happy_us
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dough: ^1.0.1
  google_nav_bar: ^5.0.5
  easy_container: ^0.0.8
  lottie: ^1.0.1
  timeline_tile: ^2.0.0
  url_strategy: ^0.2.0
  fluro: ^2.0.3
  argon_buttons_flutter: ^1.1.0
  overlay_support: ^1.2.1
  native_pdf_view: ^4.1.0
  timeago: ^3.1.0
  carousel_slider: ^4.0.0
  get_storage: ^2.0.2
  get: ^4.1.4
  dio: ^4.0.0
  flutter_linkify: ^5.0.2
  introduction_screen: ^2.1.0
  url_launcher: ^6.0.7
  pretty_dio_logger: ^1.1.1
  flutter_datetime_picker: ^1.5.1
  firebase_core: ^1.3.0
#  connectivity_plus: ^1.0.4
  rflutter_alert: ^2.0.2
  firebase_crashlytics: ^2.0.6
  firebase_analytics: ^8.1.2
  firebase_notifications_handler:
    git: "https://github.com/rithik-dev/firebase_notifications_handler"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
    - assets/docs/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans/ProductSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/ProductSans/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans/ProductSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/ProductSans/ProductSans-Black.ttf
          weight: 700
        - asset: assets/fonts/ProductSans/ProductSans-Black.ttf
          weight: 800
        - asset: assets/fonts/ProductSans/ProductSans-Black.ttf
          weight: 900